name: genome-browser
author: Lon Blauvelt (UCSC)
description: |
  Genome Browser
version: 0.0.12
services:
  ucsc-gb:
    image: "dailydreaming/genome_browser:x.12"
    port: 8001
    pdMountPath: "/data"
    pdAccessMode: "ReadWriteOnce"
    environment:
      WORKSPACE_NAME: "DRS-Test-Workspace"
      WORKSPACE_NAMESPACE: "drs-billing-project"
      GOOGLE_PROJECT: "drs-billing-project"
