name: genome-browser
author: Lon Blauvelt (UCSC)
description: |
  Genome Browser
version: 0.0.17
services:
  ucsc-gb:
    image: "gcr.io/platform-dev-178517/ucsc-genome-browser:no-min-no-tnu"
    port: 8001
    pdMountPath: "/data"
    pdAccessMode: "ReadWriteOnce"
    environment:
      WORKSPACE_NAME: "delta"
      WORKSPACE_NAMESPACE: "anvil-ucscgi-cgp-dev-BP"
      GOOGLE_PROJECT: "terra-quality-28d1bc5c"
